import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/layout/Sidebar";
import MobileNav from "@/components/layout/MobileNav";
import Providers from "../providers/providers";

const PoppinsSans = Poppins({
    subsets: ["latin"],
    weight: ["400", "500", "600", "700", "800", "900"],
    variable: "--font-poppins-sans",
});

export const metadata: Metadata = {
    title: "Tasks App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${PoppinsSans.variable} antialiased min-h-screen overflow-x-hidden`}
            >
                <Providers>
                    <div className="flex min-h-screen w-full max-w-full bg-background overflow-x-hidden">
                        <div className="hidden lg:flex">
                            <Sidebar />
                        </div>
                        <div className="flex flex-1 flex-col min-w-0">
                            <MobileNav />
                            <main className="flex-1 overflow-auto w-full min-w-0">
                                {children}
                            </main>
                        </div>
                    </div>
                </Providers>
            </body>
        </html>
    );
}
